---
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: install PHP-FPM
  apt:
    name: ['php', 'php-fpm', 'php-common', 'php-cli', 'php-curl']
    state: latest

- name: install Composer
  shell: >
    curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
    HASH=`curl -sS https://composer.github.io/installer.sig`
    php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

- name: configure php.ini
  blockinfile:
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    block: |
      date.time = Asia/Jakarta
      cgi.fix_pathinfo = 0
      memory_limit = 256M
      upload_max_filesize = 64M
      max_input_time = 360
      max_execution_time = 360
    backup: yes
  notify: restart php-fpm

- name: Composer install
  composer:
    command: install
    dest: /var/www/backend

  
- name: Create http-map
  file:
    src: http-map.jinja
    dest: /etc/nginx/sites-avilable/http-map
  notify: restart nginx