---

- name: add php repository
  apt_repository:
    repo="ppa:ondrej/php"

- name: add certbot repository
  apt_repository:
    repo="ppa:certbot/certbot"    

- name: Update&Upgrade
  apt:
    upgrade: dist
    update_cache: yes
  
- name: Set timezone
  timezone:
    name: Asia/Jakarta

- name: install certbot
  apt: 
    name: python3-certbot-nginx      